"""modified models final

Revision ID: 467cc0eebea6
Revises: 32d61fd56ae8
Create Date: 2025-10-04 11:00:05.146166

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '467cc0eebea6'
down_revision: str | Sequence[str] | None = '32d61fd56ae8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'protein_goal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'carb_goal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'fat_goal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'activity_level')
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('activity_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user', 'fat_goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'carb_goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'protein_goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
