"""added food_journal to CreateUserRequest

Revision ID: 566a7a86cb8b
Revises: d8bf541ad855
Create Date: 2025-10-06 08:15:59.762484

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '566a7a86cb8b'
down_revision: str | Sequence[str] | None = 'd8bf541ad855'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
