"""modified models weight and activity_level

Revision ID: 67a47f538a72
Revises: 467cc0eebea6
Create Date: 2025-10-04 11:42:50.353904

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67a47f538a72'
down_revision: str | Sequence[str] | None = '467cc0eebea6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('activity_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activity_level')
    op.drop_column('user', 'weight')
    # ### end Alembic commands ###
