"""changed CreateUserRequest schema

Revision ID: 9f3a86ec1dc0
Revises: bae3cce6dff5
Create Date: 2025-09-30 17:51:38.663365

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f3a86ec1dc0'
down_revision: str | Sequence[str] | None = 'bae3cce6dff5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
