"""changed token data in models to email

Revision ID: bc292513df49
Revises: 61d8de849aa8
Create Date: 2025-10-01 19:25:51.388544

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc292513df49'
down_revision: str | Sequence[str] | None = '61d8de849aa8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokendata', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('tokendata', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokendata', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tokendata', 'email')
    # ### end Alembic commands ###
