"""simplified User food_journal model

Revision ID: ca0fcb9bd46d
Revises: 566a7a86cb8b
Create Date: 2025-10-06 08:28:54.607168

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca0fcb9bd46d'
down_revision: str | Sequence[str] | None = '566a7a86cb8b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
