"""simplified CreateUserRequest

Revision ID: db58f07fbb36
Revises: ca0fcb9bd46d
Create Date: 2025-10-06 08:35:23.911317

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db58f07fbb36'
down_revision: str | Sequence[str] | None = 'ca0fcb9bd46d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
